### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by Skirmisher**
- Added `rust-toolchain.toml` override to repo, to use nightly automatically
- Updated README with info about only supporting GM8 and Windows for now
  - Also reflowed it a little I guess

Cross-compile fixes are still pending, there are a couple of hacks I've yet to resolve. (plus my energy is at a local minimum so y'know)

### CODE REVIEW

**Comment by cher-nov** [comment]
I tried to provide `rust-toolchain.toml` in July but then for me it turned out that it has nothing in common with automatically specifying the Rust channel but just hints Cargo to update specified components e.g. on every build. It will fail anyway after update if `+nightly` wasn't specified.

If it works for you, make sure that you don't have `nightly` toolchain set as default one by typing `rustup default` in the Rust console.

**Comment by Skirmisher** [comment]
I don't know how you observed that, but `rust-toolchain.toml` is explicitly a toolchain override mechanism, as described in [the rustup docs](https://rust-lang.github.io/rustup/overrides.html) (which I also linked from the README). Specifically, rustup will take care of installing the toolchain for you if you don't have it, but will *not* update it otherwise, so long as you have a toolchain that meets the specified criteria. It's possible that adding other criteria to the toml (e.g. profile) changes this behavior somehow, but my commit merely specifies the nightly toolchain and nothing further.

```
[skirmisher@sheen OpenGMK (master)]$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/skirmisher/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2021-05-03-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

i686-pc-windows-gnu
x86_64-pc-windows-gnu
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (overridden by '/home/skirmisher/buildzone/OpenGMK/rust-toolchain.toml')
rustc 1.57.0-nightly (f03eb6bef 2021-10-02)
```

**Comment by cher-nov** [comment]
That's interesting. But okay, I've investigated my issue a bit further and it turned out that the reason could be slightly different but it still makes `rust-toolchain.toml` unsuitable for us.

This is one I used back then:
```toml
[toolchain]
channel = "nightly"
targets = [ "i686-pc-windows-msvc", "x86_64-pc-windows-msvc" ]
profile = "minimal"
components = [ "rustfmt" ]
```

The actual problem seems next: when there are both `msvc` and `gnu` editions of `nightly` toolchain installed, Cargo seems to always prefer the `gnu` one, which we don't support because of https://github.com/tov/libffi-rs/issues/20. And there's no other way to specify `msvc` explicitly than set `channel = "nightly-x86_64-pc-windows-msvc"`, but this is also unsuitable because it affects `gm8emulator-wow64` as well, which had to be built for `i686` target (i.e. only as a 32-bit application).

Let's wait for comments from other developers.

**Comment by Skirmisher** [comment]
> The actual problem is that we don't support `gnu` toolchain because of [tov/libffi-rs#20](https://github.com/tov/libffi-rs/issues/20).

To be honest, it seems like a difficult proposition in the first place to try to build software on the `gnu` toolchain without having Unix-like userland tools around. I think, without special casing on the part of the `*-sys` crate, it's reasonable to expect someone with MinGW libs to also need autotools for building an autotools-based project. In turn, you'll need gcc (or clang?) binaries to build libffi itself. (`libffi-sys` already essentially replicates `configure`'s work in the MSVC context, but extending that further would add significant complexity for not much benefit...)

Anyway, even once you have the requisite tools, the `libffi-sys` build breaks when cross-compiling because the LLVM target is different from the GNU triple. On Windows (assuming you're not using an i686 *host* toolchain), this manifests when building `gm8emulator-wow64` (or cross-compiling the whole project), where Rust passes `i686-pc-windows-gnu` but `configure` expects `i686-w64-mingw32` (where the compiler is `i686-w64-mingw32-gcc`). So I had to change `libffi-sys` to use the `autotools` crate, because that makes use of the `cc` crate, which (among other things) has a big list of target triple mappings like this one, so nobody else has to duplicate that work :)

(By the way, you actually have to go out of your way in order to make `rustup` be separate between a pure-Windows environment and a Unix-like one. Even if you run it in an "MSYS" or "MINGW64" shell, it will happily install to `%USERPROFILE%\.rustup` and modify PATH in the Windows registry, ignoring `$HOME/.profile` etc., and still default to installing an `msvc` toolchain. From Rust code's perspective, there is no difference between the two environments.)

> And there's no other way to specify `msvc` explicitly than set `channel = "nightly-x86_64-pc-windows-msvc"` since rustup doesn't seem to support incomplete triples here (like `nightly-msvc` that are supported in `rustup default [toolchain]` command, which is strange). But this is also unsuitable because it will then affect `gm8emulator-wow64` as well, which had to be built for `i686` target (i.e. **only as a 32-bit application**).

There's nothing stopping you from having multiple `rust-toolchain.toml` files. There can be another one within `gm8emulator-wow64` that specifies the i686 target, that only applies when you're operating on that crate. I could possibly add that to this PR, but I'm hesitant (for reasons described below).

Anyway, you can't specify a target triple in the `channel` field (there's actually a specific error message for that, haha). And I don't think it's useful to specify the targets at the top level, since there's nothing *inherently* tying it to one Windows toolchain or another. Besides, it's not enforcing the use of those targets, just downloading `rust-std` for each one, for use by the default `nightly` toolchain. Unfortunately, when rustup is told to install "`nightly`" on Windows, it seems to force a `gnu` toolchain even when your current default is `msvc`, and *even when you have a nightly `msvc` and **not** a nightly `gnu`*. So the toolchain file is probably a bad idea after all... Seems like cause for a rustup change to happen.

The issue of selecting the GNU or MSVC target (outside of the `rustup` context) is one of the problems I was trying to figure out myself. I don't think there's going to be a clean way to deal with it, other than not specifying a target at all (in `Cargo.toml` or `rust-toolchain.toml`), and instructing users to pick whichever toolchain they want. Rust simply doesn't give us the tools to handle this situation as elegantly as I'd like.

IMO, the play here is just to document whatever steps are necessary in cases where there is no "correct" decision. Alternatively, there are solutions like `cargo xtask` and a handful of others for bundling such logic into `make`-like tasks (including `make` itself), but I think that's overkill in this case. That's why this PR has the bare minimum toolchain file to simply say "use a nightly compiler for this project" without further constraints, but I guess even that isn't going to work correctly.

**Comment by cher-nov** [comment]
> IMO, the play here is just to document whatever steps are necessary in cases where there is no "correct" decision. Alternatively, there are solutions like cargo xtask and a handful of others for bundling such logic into make-like tasks (including make itself), but I think that's overkill in this case. That's why this PR has the bare minimum toolchain file to simply say "use a nightly compiler for this project" without further constraints, but I guess even that isn't going to work correctly.

Yep, and that's why I consider that just writing `cargo +nightly` is much more easier and proper solution in current situation.
Anyway, thanks for your effort tho. I will just be glad if rustup team fix it in the future.

**Comment by Skirmisher** [comment]
One of the other rustup override options is to run `rustup override set nightly` once, which I could document here (noting the need to select MSVC or GNU) in addition to my other README changes, or I could leave that part as is if you prefer. Should I make a new PR?

**Comment by cher-nov** [comment]
I still think that this is all about solving problems that simply don't appear without `rust-toolchain.toml`. Writing `+nightly` every time in the command-line is not so much work to worth it. Moreover, there's also an ability to specify other toolchains (e.g. what if I want to check why current revision of OpenGMK doesn't compile with `stable`?), which will become noticeably complicated with the forced default one.

**Comment by Skirmisher** [comment]
> Are you going to introduce support for `gnu` toolchains? That would be great actually.

You will still need to have autotools, gcc, etc. to build libffi and so on, but what you see [here](https://github.com/OpenGMK/OpenGMK/issues/121#issuecomment-932842022) was cross-compiled for `windows-gnu` on my Linux machine :)

**Comment by cher-nov** [comment]
> You will still need to have autotools, gcc, etc. to build libffi and so on <...>

I wonder if MSYS2 can be used for this.

**Comment by cher-nov** [comment]
We're now on `stable`, so `rust-toolchain.toml` is no longer useful and was removed.
https://github.com/OpenGMK/OpenGMK/commit/98ed5e1fb747170010a0e697ad84470a3407a4bf#diff-2b1bde2cf3a858b7bf7424cb8bcbf01f35b94dc80b925d9432cbab3319ca9b4e

**Pull request closed without merging**
